package by.training.equipment_store.bean;

public enum CommandName {
    ADD_EQUIPMENT, DELETE_EQUIPMENT,
    REGISTRATION_USER, SIGN_IN, SHOW_RENTED_EQUIPMENTS,
    PRINT_REPORT, SEARCH_EQUIPMENT, RENT_EQUIPMENT, RETURN_EQUIPMENT,
    WRONG_COMMAND
}
